import { useState } from 'react';

const GiftSuggestions = ({ suggestions, query, onRegenerate, isLoading }) => {
  const [favorites, setFavorites] = useState([]);

  const toggleFavorite = (suggestion) => {
    setFavorites(prev => 
      prev.includes(suggestion)
        ? prev.filter(fav => fav !== suggestion)
        : [...prev, suggestion]
    );
  };

  const shareResults = () => {
    const text = `🎁 Awkward Gift Suggestions for ${query.relationshipType}:\n\n${suggestions.join('\n')}\n\nGenerated by AwkwardGift Finder!`;
    
    if (navigator.share) {
      navigator.share({
        title: 'Awkward Gift Suggestions',
        text: text
      });
    } else {
      navigator.clipboard.writeText(text);
      alert('Results copied to clipboard!');
    }
  };

  if (isLoading) {
    return (
      <div className="w-full max-w-4xl mx-auto">
        <div className="glass rounded-3xl p-12 shadow-2xl border border-white/20">
          <div className="text-center">
            <div className="animate-spin rounded-full h-20 w-20 border-b-2 border-white mx-auto mb-6"></div>
            <h3 className="text-2xl font-bold text-white mb-4">
              🧠 AI is thinking...
            </h3>
            <p className="text-white/70 text-lg">
              Finding the most awkwardly perfect gifts for you!
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full max-w-4xl mx-auto">
      <div className="glass rounded-3xl p-8 shadow-2xl border border-white/20">
        {/* Header */}
        <div className="text-center mb-10">
          <h2 className="text-4xl font-bold text-white mb-4">
            🎁 Your Awkward Gift Suggestions
          </h2>
          <div className="glass rounded-2xl p-4 max-w-lg mx-auto mb-6">
            <p className="text-white/80 text-lg">
              For your <span className="font-semibold text-white">{query.relationshipType}</span> who is{' '}
              <span className="font-semibold text-white">{query.personalityTraits.join(', ')}</span>
              {query.budget && (
                <span className="block mt-2 text-white/60">
                  Budget: <span className="font-semibold text-white">${query.budget}</span>
                </span>
              )}
            </p>
          </div>
          
          <div className="flex justify-center space-x-4">
            <button
              onClick={onRegenerate}
              className="btn-primary"
            >
              🔄 Regenerate
            </button>
            <button
              onClick={shareResults}
              className="btn-secondary"
            >
              📤 Share Results
            </button>
          </div>
        </div>

        {/* Suggestions */}
        <div className="space-y-6">
          {suggestions.map((suggestion, index) => (
            <div
              key={index}
              className="card-hover glass rounded-2xl p-6 border border-white/20 hover:border-white/40"
            >
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-start space-x-3">
                    <span className="text-2xl mt-1">🎁</span>
                    <p className="text-xl font-medium text-white leading-relaxed">
                      {suggestion}
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => toggleFavorite(suggestion)}
                  className={`ml-4 p-3 rounded-full transition-all duration-300 ${
                    favorites.includes(suggestion)
                      ? 'bg-red-500/20 text-red-400 hover:bg-red-500/30'
                      : 'bg-white/10 text-white/60 hover:bg-white/20 hover:text-white/80'
                  }`}
                  title={favorites.includes(suggestion) ? 'Remove from favorites' : 'Add to favorites'}
                >
                  {favorites.includes(suggestion) ? '❤️' : '🤍'}
                </button>
              </div>
            </div>
          ))}
        </div>

        {/* Favorites Section */}
        {favorites.length > 0 && (
          <div className="mt-10 glass rounded-2xl p-6 border border-red-300/30">
            <h3 className="text-2xl font-bold text-white mb-4 flex items-center">
              ❤️ Your Favorites ({favorites.length})
            </h3>
            <div className="space-y-3">
              {favorites.map((favorite, index) => (
                <div key={index} className="flex items-center justify-between bg-white/10 p-4 rounded-xl border border-white/20">
                  <span className="text-white/90 font-medium">{favorite}</span>
                  <button
                    onClick={() => toggleFavorite(favorite)}
                    className="text-red-400 hover:text-red-300 transition-colors duration-200 p-2"
                  >
                    ❌
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="mt-10 text-center">
          <div className="glass rounded-2xl p-4 max-w-md mx-auto">
            <p className="text-white/70 text-sm">
              💡 These suggestions are AI-generated and meant to be fun and memorable!
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GiftSuggestions; 